docs/proposals/dockerfile_component_detection.md

Proposal for improving port detection logic for cases where the dockerfiles are not found in a component.
PR moved from https://github.com/redhat-developer/alizer/pull/242
fixes https://github.com/devfile/api/issues/1160

adding proposal for dockerfile components

---

pkg/apis/enricher/framework/java/quarkus_detector.go
pkg/apis/enricher/framework/java/spring_detector.go
pkg/apis/enricher/go_enricher.go
pkg/utils/detector.go
resources/projects/golang-gin-app/articles/models.go
resources/projects/golang-gin-app/articles/validators.go
resources/projects/golang-gin-app/common/utils.go
resources/projects/golang-gin-app/users/models.go
resources/projects/golang-gin-app/users/validators.go
resources/projects/golang-runtime/main.go

Fixes the gosec vulnerabilities remaining from after the Alizer migration.
fixes https://github.com/devfile/api/issues/1179

fixing gosec alerts

---

README.md
docs/proposals/support_22x_devfiles.md
docs/public/alizer-spec.md
pkg/apis/model/model.go
pkg/apis/recognizer/devfile_recognizer.go
pkg/apis/recognizer/devfile_recognizer_test.go
test/check_registry/check_registry.go

This PR ensures that every variable having the name devfile does not contain a capital F for the devfile word. The only two exceptions are the `func SelectDevFileFromTypes` and `func SelectDevfilesFromTypes` which remain the same. A deprecation warning has been added in the code. Soon they will have to be removed in favor of `recognizer.MatchDevfiles` which additionally includes `devfileFilters` in order to filter the fetched stacks from the registry.
Along with code updates, changes were made in the tests and in the documentation.
fixes https://github.com/devfile/api/issues/1173

Rename DevFile to Devfile everywhere in the code.

---

.gitignore

Simply adds the `alizer` filename inside `gitignore` file. This way we can ignore the `alizer` binary in case is built

Add alizer binary to gitignore

---

README.md
docs/public/port_detection.md
pkg/apis/recognizer/component_recognizer.go
pkg/apis/recognizer/component_recognizer_test.go
pkg/cli/component/component.go
pkg/cli/component/component_test.go

This PR is part of the https://github.com/devfile/api/issues/1153 EPIC and introduces a new optimization to the port detection logic. The new flag we are creating on the `component` command is called `no-port-detection`/`n` and simply skips the port detection part of the command.
In order to do that upon `getPortDetectionStrategy` func of package `component` it checks if the global var `noPortDetection` is true. If yes it applies an early return with an empty `model.PortDetectionAlgorithm` list.
Test cases have been added inside  the new `component_test.go` file also updates have been made to the documentation.
As mentioned inside the proposal of the 1153 EPIC, we also add deprecation warning for the usage of port detection strategies.
fixes https://github.com/devfile/api/issues/1150 …

Add --no-port-detection flag to compose command

---

pkg/apis/recognizer/devfile_recognizer.go
pkg/apis/recognizer/devfile_recognizer_test.go

This PR updates the logic of `SelectDevfilesFromTypes` in order to match devfiles only for the main language of a source code if no component was found.
More detailed, upon `SelectDevfilesFromTypes`, if no component is found from the component analysis, it tries to match a devfile with the main language of the source code.
fixes https://github.com/devfile/api/issues/1219

Detect devfiles only for main language in case of no component found

---

test/check_registry/check_registry.go

This PR simply replaces a repo used by the nightly run. More detailed when the job checks for `wildfly-bootable-jar` stack we use the [examples/authentication](https://github.com/wildfly-extras/wildfly-jar-maven-plugin/tree/master/examples/authentication) source code instead of the [wildfly-devfile-examples](https://github.com/wildfly-extras/wildfly-devfile-examples.git). This way we won't use the same repo for both `wildfly` and `wildfly-bootable-jar` stacks as `starterProject` to match the given devfiles.
fixes https://github.com/devfile/api/issues/1248

[Devtools week] Fix nightly run check after wildfly stack update

---

pkg/apis/enricher/framework/dotnet/dotnet_detector.go
pkg/apis/recognizer/devfile_recognizer.go
pkg/utils/detector.go
test/check_registry/check_registry.go

Removes deprecated ioutil dependency in 4 files listed below.
% find . -name "*.go" -type f -print | xargs grep /ioutil
./test/check_registry/check_registry.go:	"io/ioutil"
./pkg/apis/enricher/framework/dotnet/dotnet_detector.go:	"io/ioutil"
./pkg/apis/recognizer/devfile_recognizer.go:	"io/ioutil"
./pkg/utils/detector.go:	"io/ioutil"
Partial fix for devfile/api#1257
os.ReadDir replacement for ioutil.ReadDir requires looping through []fs.DirEntry to access []fs.FileInfo. Consider revising error handling on this loop, I copied the previous error handling from the call to ioutil.ReadDir

chore: remove deprecated ioutil dependency

---

.github/workflows/CI.yml
.golangci.yaml
Makefile

This PR makes use of the `golangci-lint` [1] linters aggregator, configured with the `depguard`[2] linter to enforce that the deprecated `io/ioutil` [3] package is not used anymore in the code.
NOTE: Ideally, we should use all linters enabled by default by `golangci-lint`. But doing so reports a lot of issues, not relevant to the issue here (which is to enforce that 'io/ioutil' is not used anymore).
Enabling the default linters and fixing the issues reported can be done in a subsequent issue/PR.
[1] https://golangci-lint.run/
[2] https://golangci-lint.run/usage/linters/#depguard
[3] https://pkg.go.dev/io/ioutil#pkg-overview
Fixes https://github.com/devfile/api/issues/1257
```sh
$ make lint_install
$ make lint        
golangci-lint run ./... --timeout 15m
$ echo $?
0
```
Below is an …

Add golangci-lint linter to enforce that the `io/ioutil` package is not used anymore

---

.golangci.yaml
pkg/apis/enricher/docker_enricher.go
pkg/apis/enricher/enricher.go
pkg/apis/enricher/framework/dotnet/dotnet_detector.go
pkg/apis/enricher/framework/javascript/nodejs/nuxt_detector.go
pkg/apis/enricher/framework/javascript/nodejs/vue_detector.go
pkg/apis/recognizer/devfile_recognizer.go
pkg/apis/recognizer/devfile_recognizer_test.go
pkg/utils/detector.go
pkg/utils/detector_test.go
pkg/utils/langfiles/languages_file_handler.go
pkg/utils/logger_test.go
pkg/utils/testdata/bad-xml.xml
test/apis/utils.go
test/check_registry/check_registry.go
test/check_registry/check_registry_test.go

This PR enables the default linters that were disabled in a prior issue and fixes all of the issues presented by the default linters.
resolves https://github.com/devfile/api/issues/1302
You can test these changes by first running `make lint` to verify there are no more lint errors being reported. You can also run `make test` to ensure all unit tests also pass with the changes.

Enable all default golangci-lint linters and fix issues related

---

.github/workflows/release.yaml

This PR adds support for an `linux/arm64` binary on every release we make for alizer.
Part of the devtools week
An example release is here: https://github.com/thepetk/devfile-alizer/releases/tag/v1.3.1

[Devtools Week] Create linux arm64 binary after every release

---

CONTRIBUTING.md

This PR updates the `contributing.md` in order to be more consistent with the rest of the `contributing.md` files inside the `Devfile` organization. The updated document follows the `contributing.md` file of the `registry-support` repo ([here](https://github.com/devfile/registry-support/blob/main/CONTRIBUTING.md))
fixes https://github.com/devfile/api/issues/1351

[Devtools Week] Update contributing guide

---

.clomonitor.yml
README.md

This PR adds the [OpenSSF Best Practices Badge ](https://www.bestpractices.dev/en/projects/8254)to the README file as well as exempts this repository from the ArtifactHub and License Scanning checks for the [CLOMonitor](https://clomonitor.io/projects/cncf/devfile#alizer). These checks are being exempted from almost all of our repositories.
fixes https://github.com/devfile/api/issues/1384 (all but scorecard that is going to be added later)

Implement Best Practices Changes

---

.github/workflows/scorecard.yml
README.md

This PR implements the GitHub workflow required for the OpenSSF scorecard badge to be used. This scans the code on each pull request and looks for security issues. To rate repositories on their adherence to best practices it allocates a score after each run that is displayed as part of a badge in the readme.
This issue is identical to the one in devfile/library here: https://github.com/devfile/library/pull/195
fixes https://github.com/devfile/api/issues/1384

add scorecard workflow and badge

---

.github/workflows/CI.yml
.github/workflows/check_registry.yaml
.github/workflows/release.yaml
.github/workflows/stale.yaml

This PR adds an extra step in the `check_registry.yaml` workflow. In case of failure, it sends a message in a specific slack channel using a secret `SLACK_WEBHOOK_URL`.
The format of the message has been defined inside the related issue.
fixes https://github.com/devfile/api/issues/1255

Add slack notification step for nightly run failures 

---

SECURITY-INSIGHTS.yaml

As part of the CNCF defender tasks we need to add a `security-insights.md` to reach the 100% on the monitor. More information for the security insights here: https://github.com/ossf/security-insights-spec/blob/main/specification.md
Fixes https://github.com/devfile/api/issues/1392

Add SECURITY-INSIGHTS.md

---

SECURITY-INSIGHTS.yml

As suggested inside the `alizer_security` clo monitoring, a `distribution-points` section should be added inside the `SECURITY-INSIGHTS.yml`. Following examples for other repos the distribution points value can be the link to alizer's repo.
related to https://github.com/devfile/api/issues/1374

Add security-insights distribution-points

---

.github/workflows/CI.yml
.github/workflows/check_registry.yaml
.github/workflows/release.yaml

Replaces the hardcoded go version in the workflows by fetching the go version directly from the `go.mod` file.
N/A

Update workflows to point to `go.mod`

---

test/check_registry/check_registry_test.go

After the completion of https://github.com/devfile/api/issues/1604 the springboot sample has been moved to the `devfile-samples` org from the `odo-devfiles`. Currently the alizer checks are failing as we're still expecting the old url.
N/A
Tests are now passing

Fix springboot devfile sample expected URL

---

.github/workflows/release.yaml

Simply adds a sha256 checksum file for each binary that is published on every new alizer release
Fixes https://github.com/devfile/api/issues/1624
_Testing and documentation do not need to be complete in order for this PR to be approved. However, tracking issues must be opened for missing testing/documentation._
_Explain what tests you personally ran to ensure the changes are functioning as expected._
_Instructions for the reviewer on how to test your changes._
Example release can be found here https://github.com/thepetk/devfile-alizer/releases/tag/v0.0.1

Add checksum step for release workflow

---

.github/workflows/scorecard.yml
Makefile
go.mod
test/apis/component_recognizer_test.go
test/apis/language_recognizer_test.go
test/apis/utils.go

Simply upgrades the go version of alizer to 1.23
partially fixes https://github.com/devfile/api/issues/1671
_Testing and documentation do not need to be complete in order for this PR to be approved. However, tracking issues must be opened for missing testing/documentation._
_Explain what tests you personally ran to ensure the changes are functioning as expected._
_Instructions for the reviewer on how to test your changes._
_Any notes you would like to include for the reviewer._

Upgrade go version to 1.23
